/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author del
 */
public class InventarioForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form InventarioForm
     */
    JDesktopPane dp;
    int xx, xy;
    public InventarioForm(JDesktopPane dp) {
        this.dp = dp;
        initComponents();
        ((BasicInternalFrameUI) this.getUI()).setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        panelComp = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelCat = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        backBoton = new javax.swing.JButton();
        panelFabri = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        panelTR = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setBorder(null);

        jPanel3.setBackground(new java.awt.Color(69, 126, 170));

        panelComp.setBackground(new java.awt.Color(69, 126, 170));
        panelComp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelComp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelCompMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelCompMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelCompMouseExited(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Automation_25px.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Componentes");

        javax.swing.GroupLayout panelCompLayout = new javax.swing.GroupLayout(panelComp);
        panelComp.setLayout(panelCompLayout);
        panelCompLayout.setHorizontalGroup(
            panelCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCompLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(23, 23, 23))
        );
        panelCompLayout.setVerticalGroup(
            panelCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCompLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(panelCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        panelCat.setBackground(new java.awt.Color(69, 126, 170));
        panelCat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelCat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelCatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelCatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelCatMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Categorías");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Bus_25px.png"))); // NOI18N

        javax.swing.GroupLayout panelCatLayout = new javax.swing.GroupLayout(panelCat);
        panelCat.setLayout(panelCatLayout);
        panelCatLayout.setHorizontalGroup(
            panelCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCatLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(22, 22, 22))
        );
        panelCatLayout.setVerticalGroup(
            panelCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        backBoton.setBackground(new java.awt.Color(69, 126, 170));
        backBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Long_Arrow_Left_40px.png"))); // NOI18N
        backBoton.setBorder(null);
        backBoton.setBorderPainted(false);
        backBoton.setContentAreaFilled(false);
        backBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBotonMouseClicked(evt);
            }
        });

        panelFabri.setBackground(new java.awt.Color(69, 126, 170));
        panelFabri.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelFabri.setPreferredSize(new java.awt.Dimension(216, 50));
        panelFabri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelFabriMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelFabriMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelFabriMouseExited(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Factory_25px.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fabricantes");

        javax.swing.GroupLayout panelFabriLayout = new javax.swing.GroupLayout(panelFabri);
        panelFabri.setLayout(panelFabriLayout);
        panelFabriLayout.setHorizontalGroup(
            panelFabriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFabriLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(27, 27, 27))
        );
        panelFabriLayout.setVerticalGroup(
            panelFabriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFabriLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFabriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        panelTR.setBackground(new java.awt.Color(69, 126, 170));
        panelTR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelTR.setPreferredSize(new java.awt.Dimension(216, 50));
        panelTR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelTRMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelTRMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelTRMouseExited(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Piston_25px_1.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tipos de repuestos");

        javax.swing.GroupLayout panelTRLayout = new javax.swing.GroupLayout(panelTR);
        panelTR.setLayout(panelTRLayout);
        panelTRLayout.setHorizontalGroup(
            panelTRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTRLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(27, 27, 27))
        );
        panelTRLayout.setVerticalGroup(
            panelTRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTRLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(panelTRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelComp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelCat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(backBoton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelFabri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelTR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(backBoton)
                .addGap(39, 39, 39)
                .addComponent(panelComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelFabri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelTR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDesktopPane1.setBackground(new java.awt.Color(238, 238, 238));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 823, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 657, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1)
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jDesktopPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelCompMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCompMouseClicked
        ComponentesForm cp;
        try {
            cp = new ComponentesForm();
            jDesktopPane1.removeAll();
            jDesktopPane1.add(cp);
            cp.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(InventarioForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_panelCompMouseClicked

    private void panelCompMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCompMouseEntered
        //panelComp.setBackground(new java.awt.Color(48, 184, 113));
        panelComp.setBackground(new java.awt.Color(48, 84, 113));
    }//GEN-LAST:event_panelCompMouseEntered

    private void panelCompMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCompMouseExited
        panelComp.setBackground(new java.awt.Color(69, 126, 170));
    }//GEN-LAST:event_panelCompMouseExited

    private void panelCatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCatMouseEntered
        panelCat.setBackground(new java.awt.Color(48, 84, 113));
    }//GEN-LAST:event_panelCatMouseEntered

    private void panelCatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCatMouseExited
        panelCat.setBackground(new java.awt.Color(69, 126, 170));
    }//GEN-LAST:event_panelCatMouseExited

    private void backBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBotonMouseClicked
        try {
            //this.dispose();
            MenuPrincipal mp = new MenuPrincipal(dp);
            //dp.removeAll();
            dp.add(mp);
            mp.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(InventarioForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_backBotonMouseClicked

    private void panelFabriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelFabriMouseClicked
        FabricantesForm ff;
        try {
            ff = new FabricantesForm();
            jDesktopPane1.removeAll();
            jDesktopPane1.add(ff);
            ff.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(InventarioForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_panelFabriMouseClicked

    private void panelFabriMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelFabriMouseEntered
        panelFabri.setBackground(new java.awt.Color(48, 84, 113));
    }//GEN-LAST:event_panelFabriMouseEntered

    private void panelFabriMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelFabriMouseExited
        panelFabri.setBackground(new java.awt.Color(69, 126, 170));
    }//GEN-LAST:event_panelFabriMouseExited

    private void panelTRMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelTRMouseEntered
        panelTR.setBackground(new java.awt.Color(48, 84, 113));
    }//GEN-LAST:event_panelTRMouseEntered

    private void panelTRMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelTRMouseExited
        panelTR.setBackground(new java.awt.Color(69, 126, 170));
    }//GEN-LAST:event_panelTRMouseExited

    private void panelCatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCatMouseClicked
        CategoriasForm cf;
        try {
            cf = new CategoriasForm();
            jDesktopPane1.removeAll();
            jDesktopPane1.add(cf);
            cf.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(InventarioForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_panelCatMouseClicked

    private void panelTRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelTRMouseClicked
        TipoCompForm cpf;
        try {
            cpf = new TipoCompForm();
            jDesktopPane1.removeAll();
            jDesktopPane1.add(cpf);
            cpf.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(InventarioForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_panelTRMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBoton;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel panelCat;
    private javax.swing.JPanel panelComp;
    private javax.swing.JPanel panelFabri;
    private javax.swing.JPanel panelTR;
    // End of variables declaration//GEN-END:variables
}
